## 벡터의 덧셈, 뺄셈, 곱셈

In [1]:
import numpy as np

x1 = np.array([1,2,3])
x2 = np.array([3,2,1])

In [2]:
x1 + x2

array([4, 4, 4])

In [3]:
x1 - x2

array([-2,  0,  2])

In [4]:
x1 * x2

array([3, 4, 3])

## 벡터의 노름(norm) 구하기

In [7]:
def l1_norm(x):
    x_norm = np.abs(x)
    x_norm = np.sum(x_norm)
    return x_norm

def l2_norm(x):
    x_norm = x*x
    x_norm = np.sum(x_norm)
    x_norm = np.sqrt(x_norm)
    return x_norm

test = [-1, 2, -3]
print(l1_norm(test))

print(l1_norm(x1))
print(l2_norm(x2))

6
6
3.7416573867739413


## 두 벡터 사이의 각도 구하기

In [6]:
# 내적은 np.inner을 사용하여 구한다.

def angle(x,y):
    v = np.inner(x,y) / (l2_norm(x) * l2_norm(y))
    theta = np.arccos(v)
    return theta

x1 = np.array([1,2,3])
x2 = np.array([3,2,1])

print(angle(x1,x2))

0.7751933733103613
