## 행렬

In [3]:
import numpy as np

X = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

print(X)
print(X.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


## 행렬 곱셈

In [13]:
X = np.array([[1,2,3],
              [4,5,0],
              [9,-1,-5]])

Y = np.array([[0,1],
             [2,3],
             [-5,-10]])

Z = np.array([[1,1,1],
             [2,2,2]])

# numpy 행렬 곱셈은 @ 연산 사용
print('행렬 곱셈\n',X@Y) # X의 열의 개수와 Y의 행의 수가 같아야함
print()
print('numpy의 행렬 곱셈\n',np.inner(X,Z))  # 두 행의 크기가 같아야함

행렬 곱셈
 [[-11 -23]
 [ 10  19]
 [ 23  56]]

numpy의 행렬 곱셈
 [[ 6 12]
 [ 9 18]
 [ 3  6]]


## 역행렬

### 행과 열의 수가 같아야함! 주의!

In [18]:
X = np.array([[13,2,1],
             [1,1,1],
              [0,2,-5]])

print(np.linalg.inv(X))
print()
print( X @ np.linalg.inv(X))  # 항등 행렬

[[ 0.08860759 -0.15189873 -0.01265823]
 [-0.06329114  0.82278481  0.15189873]
 [-0.02531646  0.32911392 -0.13924051]]

[[ 1.00000000e+00  5.55111512e-17  0.00000000e+00]
 [-6.93889390e-18  1.00000000e+00  2.77555756e-17]
 [ 6.93889390e-18 -5.55111512e-17  1.00000000e+00]]


## 유사역행렬

In [20]:
X = np.array([[15,2,1],
             [1,-10,1],
              [0,3,-5]])

print(np.linalg.pinv(X))
print()
print( X @ np.linalg.pinv(X))  # 항등 행렬

[[ 0.06545961  0.01810585  0.01671309]
 [ 0.00696379 -0.10445682 -0.01949861]
 [ 0.00417827 -0.06267409 -0.21169916]]

[[ 1.00000000e+00 -6.93889390e-17 -5.55111512e-17]
 [ 2.34187669e-17  1.00000000e+00 -1.11022302e-16]
 [-9.54097912e-18  1.24900090e-16  1.00000000e+00]]
