pip install tensorboardX
pip install jupyter-tensorboard
pip install keras
pip install h5py
pip install tensorflow --user
!python -m pip install --upgrade tensorflow --user

In [1]:
import tensorflow as tf

print(tf.__version__)

2.4.1


In [5]:
import tensorflow as tf

# 행과 열 만들기
matrix1 = tf.constant( [ [  3, 3  ]   ] )
matrix1

matrix2 = tf.constant( [ [  2 ] , [2]   ] )
matrix2

res = tf.matmul(matrix1, matrix2)
print(res)


tf.Tensor([[12]], shape=(1, 1), dtype=int32)


In [2]:
import tensorflow as tf

# 행과 열 만들기
matrix1 = tf.constant( [ [  3, 3  ]   ] )
matrix1

matrix2 = tf.constant( [ [  2 ] , [2]   ] )
matrix2
print(matrix2.shape)  # 2,1

res = tf.matmul(matrix1, matrix2)
print(res)

x = tf.constant(([1,2,3,4]),shape=(2,2))
res02 = tf.math.multiply(x,x)
print(res02)

hap = tf.math.add(x,x)
print(hap)

(2, 1)
tf.Tensor([[12]], shape=(1, 1), dtype=int32)
tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 4]
 [6 8]], shape=(2, 2), dtype=int32)


In [17]:
import tensorflow as tf

# 행열 연산을 구현해보자 -> 3.0 * (2.0 + 5.0)
input01 = tf.constant( [ 3.0   ] )
input02 = tf.constant( [ 2.0   ] )
input03 = tf.constant( [ 5.0   ] )

# 1.
hap = tf.add(input02, input03)
res = tf.multiply(input01,hap)
print(hap)
print(res)

# 2.
res02 = tf.multiply( input01, tf.add(input02, input03))
print(res02)

tf.Tensor([7.], shape=(1,), dtype=float32)
tf.Tensor([21.], shape=(1,), dtype=float32)
tf.Tensor([21.], shape=(1,), dtype=float32)


In [19]:
import tensorflow as tf

# 기본 실행 메소드 사용
print(tf.executing_eagerly())
x=[[2]]
m = tf.matmul(x,x)
print("hello,{}".format(m))

True
hello,[[4]]


In [26]:
# 반환 작업
a = tf.constant([[1,2],[3,4]])
print(a.numpy()) # 메소드
print(type(a.numpy()))
print(a.numpy,'\n') # 속성
print(a.shape)
print(a)
print(a.dtype)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>> 

(2, 2)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
<dtype: 'int32'>


In [30]:
# 브로드캐스팅(Broadcasting) 지원
b = tf.add(a,1)
print(b)

# 연산자 오버로딩 지원
print(a*b)

# numpy 지원
import numpy as np

res = np.multiply(a,b)
print(res, type(res))

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)
[[ 2  6]
 [12 20]] <class 'numpy.ndarray'>


In [8]:
# Variable : 변수 자동 변환

name = tf.Variable('주아', tf.string)
kor = tf.Variable(100, tf.int32)
eng = tf.Variable(50, tf.int32)
tot = kor + eng
print(tot)
print(tot.numpy())

print(name.numpy())

tf.Tensor(150, shape=(), dtype=int32)
150
b'\xec\xa3\xbc\xec\x95\x84'


In [14]:
a = tf.Variable( [3, 256, 1234.56], tf.float32 )
b = tf.Variable([1,2,3,4,5], tf.float32)
c = tf.Variable([12.3-4.85j, 7.5-6.12j], tf.complex64)

print(a.numpy())
print(a.dtype)
print(b.numpy())
print(c.numpy())

[   3.    256.   1234.56]
<dtype: 'float32'>
[1 2 3 4 5]
[12.3-4.85j  7.5-6.12j]


In [16]:
# tf.zeors() , tf.rank() : tnesor 차원을 리턴 받기
# 배치 * 높이 * 너비 * 색상

img = tf.zeros( [10, 299, 299, 3])
res = tf.rank(img)

print(type(img))
print(img)
print(res)

<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(4, shape=(), dtype=int32)


In [17]:
# 요소를 리턴
abc = tf.Variable( [1,2,3,4] )
abc_1 = abc[2]

print(abc_1)

tf.Tensor(3, shape=(), dtype=int32)


In [19]:
# tf의 객체를 Variable로 연동

my_val = tf.Variable( tf.zeros(2,3,4) ) # 변수
print(my_val.numpy())

my_val_2 = tf.constant( tf.zeros(2,2,3) ) # 상수
print(my_val_2.numpy())

[0 0]
[0. 0.]


In [23]:
# 변수 자동 변환
v = tf.Variable(0.0)
v.numpy()

# w는 v값 기준으로 계산되는 tf.Tensor
# 변수가 수식으로 사용하게 되면 tf.Tensor로 변환됨
w = v + 1  
w

a = tf.Variable(1.0)
a.assign_add(1)
print(a)
print(a.numpy())
print(a.read_value())  # 2.0

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>
2.0
tf.Tensor(2.0, shape=(), dtype=float32)


# 텐서 = 스칼라 또는 벡터 또는 매트릭스

In [57]:
import tensorflow as tf

# 3*2행의 float32값을 이용해서 값을 구현해보자
'''
1  2
3  4
5  6
'''
a = tf.Variable([[1,2],[3,4],[5,6]], dtype=tf.float32)
print(a.numpy())
print('\n')

# 전체 -값으로 변경해보자
a.assign([[-1,-2],[-3,-4],[-5,-6]])
print(a.numpy())
print('\n')

# 3*2 행의 값을 모두 0으로 초기화 float32
a = tf.Variable(tf.zeros([3,2]), dtype=tf.float32)
print(a.numpy())
print('\n')

# 3*2 행 값의 요소 모두를 평균은 0, 표준편차는 0.1의 정규난수로 초기화 시키자
# tf.random.normal()
a = tf.random.normal((3,2), mean=0, stddev=0.1)
print(a.numpy())
print(a.dtype)

# 3*2 행 값의 요소를 모두 -1 ~3 까지의 범위의 균일값을 난수로 초기화 시키자
a = tf.random.uniform((3,2), minval= -1, maxval=3)
print('\n',a.numpy())

[[1. 2.]
 [3. 4.]
 [5. 6.]]


[[-1. -2.]
 [-3. -4.]
 [-5. -6.]]


[[0. 0.]
 [0. 0.]
 [0. 0.]]


[[-0.0532045  -0.08467827]
 [-0.00690944 -0.02565944]
 [-0.05182331  0.13943648]]
<dtype: 'float32'>

 [[-0.17129326  2.7399054 ]
 [-0.36470127  2.5724883 ]
 [ 1.7593684   0.04449368]]


In [25]:
# f(x) 표현하는 연산 시스템
# log(x), exp(x), sin(x), cos(x), sigmoid(x), tanh(x) 등

a = tf.constant([1,2,3], tf.float32)
b = tf.math.log(a)
print(b.numpy())

c = tf.math.sigmoid(a)
print(c.numpy())

d = tf.math.tanh(a)
print(d.numpy())

[0.        0.6931472 1.0986123]
[0.7310586  0.8807971  0.95257413]
[0.7615942 0.9640276 0.9950547]


## softmax : 로지스틱 함수를 다차원으로 만든것
- 다항 로지스틱 회귀로 출력에 대한 확률분포 네트워크 출력을 하는 정규화
- 신경망의 활성화 함수로 자주 사용한다.
- z = K로 실수값을 벡터로 받아서 입력 숫자에 지수에 비례하는 K개의 확률분포 정규화 시킨것


- tf.nn.softmax(logits, axis, name)
- softmax = tf.exp(logits) / tf.reduce_sum(tf.exp(logits), axis)

< tf.nn.softmax(x) >

입력 인수 x : 텐서, 정수 상수 텐서, 변수 상수

출력 값 : 
1. x의 각 요소마다 exp()을 계산해서 A에 할당
2. A의 요소를 모두 더해서 임의 변수 a에 넣는다
3. A의 요소를 a로 나누어서 출력 텐서를 한다
4. 출력 텐서 각 요소의 값은 확률을 나타낸다

In [63]:
a = tf.constant([1,2,3], tf.float32)
b = tf.nn.softmax(a)
print(b.numpy()) # 확률분포

b = tf.reduce_sum(a)
print(b.numpy()) # 확률분포

[0.09003057 0.24472848 0.66524094]
6.0


In [27]:
# 사용자 오퍼레이션(노드) 만들기
'''
@tf.function
def 함수명():
    연산
    return
'''

# (a+b)*c  - myOP(a,b,c)
@tf.function
def myOP(a,b,c):
    t = tf.math.add(a,b)
    return tf.math.multiply(t,c)

A = tf.constant( [1,2], tf.float32 )
B = tf.constant( [3,4], tf.float32 )
C = tf.constant( [5,6], tf.float32 )
D = myOP(A,B,C)  
print(D, type(D))  # tf.Tensor([20. 36.], shape=(2,), dtype=float32)
print(D.numpy())

tf.Tensor([20. 36.], shape=(2,), dtype=float32) <class 'tensorflow.python.framework.ops.EagerTensor'>
[20. 36.]


In [34]:
# 사용자 자료형 만들기
# tf.Module 상속 받아 구현
# tf.Module 인스턴스는 Variable을 포함해서 다른 모듈들을 탐색할 수 있다.
# trainable_variables = 훈련 가능한 변수를 리턴

class MyModuleOne(tf.Module):
    def __init__(self):
        self.VO = tf.Variable(1.0)
        self.VS = [ tf.Variable(x) for x in range(10) ]
        
class MyOtherModule(tf.Module):
    def __init__(self):
        self.m = MyModuleOne()
        self.v = tf.Variable(10.0)
        
m = MyOtherModule()
print(len(m.variables))
print(m.variables)
print()
print(m.m)  # 11은 m.m에서 다른 값은 m.v에서
print(m.v)

12
(<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=10.0>, <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=0>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=4>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=5>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=6>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=7>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=8>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=9>)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=10.0>


In [39]:
# 케라스
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential( 
    [
        layers.Dense(2, activation="relu", name="layer1"),
        layers.Dense(3, activation="relu", name="layer2"),
        layers.Dense(4, name="layer3")
    ]
)

print(model)

In [46]:
# 순차모델 만들기
import tensorflow as tf

model = keras.Sequential( 
    [
        layers.Dense(100, name="layer0", input_shape=(1000,)),
        layers.Dense(10, name="layer1"),
        layers.Dense(1, name="layer2")
    ]
)

model.summary()
print('\n')
print(type(model.layers[0]))
print(model.layers[0].name)

d = {k.name : i for i, k in enumerate(model.layers)}
print(d)
print(d['layer0'])

layer_name = [k.name for k in model.layers]
print(layer_name)

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
layer0 (Dense)               (None, 100)               100100    
_________________________________________________________________
layer1 (Dense)               (None, 10)                1010      
_________________________________________________________________
layer2 (Dense)               (None, 1)                 11        
Total params: 101,121
Trainable params: 101,121
Non-trainable params: 0
_________________________________________________________________


<class 'tensorflow.python.keras.layers.core.Dense'>
layer0
{'layer0': 0, 'layer1': 1, 'layer2': 2}
0
['layer0', 'layer1', 'layer2']


심층 신경망은 학습한 모든 변환을 수치 데이터 텐서에 적용하는 텐서 연산을 사용한다.

  ex) 텐서 덧셈, 텐서 곱셈
    
tf.keras.layers.Dense(1, name='Layer_2')  -> 신경망을 만들었다. 층을 설정했다.

데이터 -> 학습 구조 모델링 -> 학습 수행 -> 평가

In [ ]:
# 간단한 공식을 이용하여 값을 전달 후 평가로 예측 값을 구현
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
import numpy as np

# y= ax + b
# 5 = a2 + b3 = a1 + b7 = a*3 + b

# 데이터 지정
x = np.array([1,2,3,4,5])
y = x*2+1
print(x, y)

# 학습 구조 모델링
model = Sequential() # 레이어를 층층이 쌓아주는 메소드
model.add(Dense(1, input_shape = (1,))) # 1개 쌓기

# SGD (Stochastic gradient descent : 확률적 경사 하강법)
# mes (Mean Squared Error : 평균 제곱 오차)
model.compile('SGD','mse') # 이 방법으로 학습

# 학습 수행 : 몇 번을 어떻게 할 것인가?
model.fit( x,y, epochs=1000, verbose=0 ) # epochs -> 학습 횟수, 학습을 많이 할 수록 predict에서 y값과 가까운 값을 리턴

# 평가
print('y : ', y, '\n'
      ,'predict : ', model.predict(x).flatten() )


[1 2 3 4 5] [ 3  5  7  9 11]


In [77]:
# tf.GradientTape API : 텐서플로는 자동 미분하는 API를 제공
# context 안에 실행된 모든 연산을 tape에 기록한다
# 후진방식 자동 미분을 사용해서 tape에 기록된 연산 결과를 계산한다
# 기울기를 구하는 클래스 : 정밀한 예측 모델을 만들려면 적당히 선택한 매개 변수에서
# 예상한 값과 실제 결과를 비교해서 가능한 차이가 적게 매개 변수를 조정하게 된다.
# 이때 필요한 것이 GradientTape

x = tf.ones((2,2))

with tf.GradientTape() as t :
    t.watch(x)
    y = tf.reduce_sum(x)
    z = tf.multiply(y,y)
    
dz_dx = t.gradient(z,x) # 입력텐서 x에 대한 z값
for i in [0,1] :
    for j in [0,1]:
        assert dz_dx[i][j] == 8.0
#         dz_dx[i][j].numpy() == 8.0 # 위와 동일 결과
        print(dz_dx[i][j])
    

tf.Tensor(8.0, shape=(), dtype=float32)
tf.Tensor(8.0, shape=(), dtype=float32)
tf.Tensor(8.0, shape=(), dtype=float32)
tf.Tensor(8.0, shape=(), dtype=float32)
